//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nitrocid.Extras.SftpShell.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddonResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddonResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nitrocid.Extras.SftpShell.Resources.AddonResources", typeof(AddonResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;Name&quot;: &quot;FTP&quot;,
        ///        &quot;Desc&quot;: &quot;This section lets you configure how the FTP shell works.&quot;,
        ///        &quot;Keys&quot;: [
        ///            {
        ///                &quot;Name&quot;: &quot;Prompt Preset&quot;,
        ///                &quot;Type&quot;: &quot;SPreset&quot;,
        ///                &quot;Variable&quot;: &quot;FtpPromptPreset&quot;,
        ///                &quot;ShellType&quot;: &quot;FTPShell&quot;,
        ///                &quot;Description&quot;: &quot;&quot;
        ///            },
        ///            {
        ///                &quot;Name&quot;: &quot;Log FTP username&quot;,
        ///                &quot;Type&quot;: &quot;SBoolean&quot;,
        ///                &quot;Variable&quot;: &quot;FtpLoggerUsername&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SftpSettings {
            get {
                return ResourceManager.GetString("SftpSettings", resourceCulture);
            }
        }
    }
}
