'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Kernel_Simulator.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''~~- Information about this manual page:
        '''-TITLE:Available command-line arguments
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''~~- Make sure that all of the command-line arguments that are available in the kernel is put.
        '''-BODY START-
        '''How do I run command-line arguments?
        '''
        '''You can run these arguments to make the simulator behave differently, by running Kernel Simulator like below examples:
        '''
        '''- &quot;Kernel Simulator.exe&quot; promptArgs
        '''- &quot;Kernel Simulator.exe&quot; testMod ModToBeTested.m
        '''
        '''Useful [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Available_command_line_arguments() As String
            Get
                Return ResourceManager.GetString("Available_command_line_arguments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''~~- Information about this manual page:
        '''-TITLE:Available commands
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''~~- Make sure that all of the commands that are available in the kernel is put.
        '''-BODY START-
        '''Administrative commands:
        '''
        '''1. adduser: You can add the user&apos;s name whenever you need, with the password if required. However, passwords are required to ensure security. Currently, it has an argument of &quot;adduser &lt;username&gt; &lt;password&gt;.&quot;
        '''2. perm: You can manage user&apos;s permission settin [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Available_commands() As String
            Get
                Return ResourceManager.GetString("Available_commands", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''~~- Information about this manual page:
        '''-TITLE:Available FTP commands
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''~~- Make sure that all of the commands that are available in the FTP shell is put.
        '''-BODY START-
        '''Administrative commands:
        '''
        '''1. delete (del): You can delete unwanted files from the server
        '''2. rename (ren): Rename the mis-named files into their correct names in the server
        '''3. upload (put): Send your local file to the server
        '''
        '''Normal user commands:
        '''
        '''1. currlocaldir (pwdl) [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Available_FTP_commands() As String
            Get
                Return ResourceManager.GetString("Available_FTP_commands", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''~~- Information about this manual page:
        '''-TITLE:Available kernel arguments
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''~~- Make sure that all of the kernel arguments that are available in the kernel is put.
        '''-BODY START-
        '''How to run arguments? and how do I make the prompt appear?
        '''
        '''An argument to the kernel is the option of which the kernel or parts of it will behave differently based on the options you have chosen. It will be run on the start of the kernel, and if no arguments were sp [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Available_kernel_arguments() As String
            Get
                Return ResourceManager.GetString("Available_kernel_arguments", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Available manual pages
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''Check out:
        '''
        '''1. Introduction to the Kernel: This page shows you the introduction about the kernel, how was Unix and Linux built and improved over the years of development, and a brief description about our kernel, Eofla Kernel, which will get a name.
        '''2. Available commands: This page shows you available commands in the kernel. You can also show them using help command.
        '''3. History of Kernel Simulato [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Available_manual_pages() As String
            Get
                Return ResourceManager.GetString("Available_manual_pages", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Available commands: {0} &lt;=+=&gt; Kěyòng mìnglìng: {0}
        '''Write command: &lt;=+=&gt; Xiě mìnglìng:
        '''Command injection has been cancelled. &lt;=+=&gt; Mìnglìng zhùrù yǐ bèi qǔxiāo.
        '''Separate boot arguments with commas without spaces, for example, &apos;motd,gpuprobe&apos; &lt;=+=&gt; Shǐyòng dòuhào fēngé yǐndǎo cānshù, bù dài kònggé, lìrú&apos;motd,gpuprobe&apos;
        '''Separate commands on &apos;cmdinject&apos; with colons with spaces, for example, &apos;cmdinject setthemes Hacker : beep 1024 0.5&apos; &lt;=+=&gt; &apos;Cmdinject&apos; shàng de mìnglìng yǔ dài kònggé de màohào fēnkāi, lìrú&apos;c [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property chi() As String
            Get
                Return ResourceManager.GetString("chi", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''~~- Information about this manual page:
        '''-TITLE:Configuration for your Kernel
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''What is the Config?
        '''
        '''The config is the configuration for your kernel that stores more kernel options that couldn&apos;t be edited in either the arguments or command-line arguments. Some commands do change the config file. KS Config Tool is suitable for editing configuration.
        '''
        '''There are many sections to make reading the config file easier. They are 6 sect [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Configuration_for_your_Kernel() As String
            Get
                Return ResourceManager.GetString("Configuration_for_your_Kernel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Available commands: {0}
        '''Write command: 
        '''Command injection has been cancelled. 
        '''Separate boot arguments with commas without spaces, for example, &apos;motd,gpuprobe&apos; 
        '''Separate commands on &apos;cmdinject&apos; with colons with spaces, for example, &apos;cmdinject setthemes Hacker : beep 1024 0.5&apos; 
        '''Note that the &apos;debug&apos; argument does not fully cover the kernel. 
        '''bargs: The requested argument {0} is not found. 
        '''bargs: Unrecoverable error in argument:  
        '''Available arguments: {0} 
        '''Arguments (&apos;help&apos; for help):  
        '''Injected ar [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property eng() As String
            Get
                Return ResourceManager.GetString("eng", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Available commands: {0} &lt;=+=&gt; Commandes disponibles: {0}
        '''Write command: &lt;=+=&gt; Commande d&apos;écriture:
        '''Command injection has been cancelled. &lt;=+=&gt; L&apos;injection de commande a été annulée.
        '''Separate boot arguments with commas without spaces, for example, &apos;motd,gpuprobe&apos; &lt;=+=&gt; Séparez les arguments de démarrage par des virgules sans espaces, par exemple &quot;motd,gpuprobe&quot;
        '''Separate commands on &apos;cmdinject&apos; with colons with spaces, for example, &apos;cmdinject setthemes Hacker : beep 1024 0.5&apos; &lt;=+=&gt; Séparez les commandes s [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property fre() As String
            Get
                Return ResourceManager.GetString("fre", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Available commands: {0} &lt;=+=&gt; Verfügbare Befehle: {0}
        '''Write command: &lt;=+=&gt; Schreibbefehl:
        '''Command injection has been cancelled. &lt;=+=&gt; Die Befehlsinjektion wurde abgebrochen.
        '''Separate boot arguments with commas without spaces, for example, &apos;motd,gpuprobe&apos; &lt;=+=&gt; Trennen Sie Boot-Argumente durch Kommas ohne Leerzeichen, z. B. &quot;motd, gpuprobe&quot;
        '''Separate commands on &apos;cmdinject&apos; with colons with spaces, for example, &apos;cmdinject setthemes Hacker : beep 1024 0.5&apos; &lt;=+=&gt; Trennen Sie Befehle in &apos;cmdinject&apos; mit Doppe [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ger() As String
            Get
                Return ResourceManager.GetString("ger", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''~~- Information about this manual page:
        '''-TITLE:History of Kernel Simulator
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''Pre-release
        '''
        '''Before the release of 0.0.1, we are working on the PowerPoint OS collection almost 2 years ago, and that used VBA (VB6) macros on Office 2007, and while we are working on the PUNIX-based PPT OS, the macro amount is too much so we have removed the entire OS remaining only 2 OS. In that way, we have learned how to develop VB.NET, and started  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property History_of_Kernel_Simulator() As String
            Get
                Return ResourceManager.GetString("History_of_Kernel_Simulator", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Available commands: {0} &lt;=+=&gt; upalabdh aadesh: {0}
        '''Write command: &lt;=+=&gt; kamaand likhen:
        '''Command injection has been cancelled. &lt;=+=&gt; kamaand injekshan radd kar diya gaya hai.
        '''Separate boot arguments with commas without spaces, for example, &apos;motd,gpuprobe&apos; &lt;=+=&gt; bina spes ke alpaviraam ke saath alag boot tark, udaaharan ke lie, &apos;motd, gpuprobe&apos;
        '''Separate commands on &apos;cmdinject&apos; with colons with spaces, for example, &apos;cmdinject setthemes Hacker : beep 1024 0.5&apos; &lt;=+=&gt; rikt sthaan vaale kolan ke saath chmdinja [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ind() As String
            Get
                Return ResourceManager.GetString("ind", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''~~- Information about this manual page:
        '''-TITLE:Introduction to the Kernel
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''What is the Kernel? How about Kernel Simulator?
        '''
        '''The kernel in general is a computer program that is the core of a computer&apos;s operating system, with complete control over everything in the system. On most systems, it is one of the first programs loaded on start-up (after the bootloader). It handles the rest of start-up as well as input/output requests fr [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Introduction_to_the_Kernel() As String
            Get
                Return ResourceManager.GetString("Introduction_to_the_Kernel", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:How to make your own mod for the kernel
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''What is the mod for the kernel?
        '''
        '''The mod is the source code file that loads on boot, and can add extensions to the kernel, the shell, and everything. It can also respond to events. However, the mod can only have one command, and a command code.
        '''
        '''This is useful if you want to add your own extensions to the kernel, like event handlers for the kernel.
        '''
        '''Can I make my own screensave [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Modding_guide() As String
            Get
                Return ResourceManager.GetString("Modding_guide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Available commands: {0} &lt;=+=&gt; Comandos disponíveis: {0}
        '''Write command: &lt;=+=&gt; Comando de gravação:
        '''Command injection has been cancelled. &lt;=+=&gt; A injeção de comando foi cancelada.
        '''Separate boot arguments with commas without spaces, for example, &apos;motd,gpuprobe&apos; &lt;=+=&gt; Separe os argumentos de inicialização com vírgulas sem espaços, por exemplo, &apos;motd, gpuprobe&apos;
        '''Separate commands on &apos;cmdinject&apos; with colons with spaces, for example, &apos;cmdinject setthemes Hacker : beep 1024 0.5&apos; &lt;=+=&gt; Comandos separados em &apos;cmdi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ptg() As String
            Get
                Return ResourceManager.GetString("ptg", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;adduser&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''adduser command
        '''
        '''Summary: You can add the user&apos;s name whenever you need, with the password if required.
        '''
        '''Description
        '''
        '''If you need to add a person that wants to use the kernel, you can add users for them, and let them specify the password if they need. This way, adduser will only create an account and gets the permissions for the new user ready, and the new user will be a normal account for sec [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___adduser() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___adduser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;alias&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''alias command
        '''
        '''Summary: You can set an alternative shortcut to the command if you want to use shorter words for long commands.
        '''
        '''Description
        '''
        '''Some commands in this kernel are long, and some people doesn&apos;t write fast on computers. The alias command fixes this problem by providing the shorter terms for long commands.
        '''
        '''You can also use this command if you plan to make scripts if the real file syst [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___alias() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___alias", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;arginj&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''alias command
        '''
        '''Summary: You can set the arguments to launch at reboot.
        '''
        '''Description
        '''
        '''If you need to reboot your kernel to run the debugger, or if you want to disable hardware probing to save time when booting, then this command is for you. It allows you to set arguments so they will be run once at each reboot.
        '''
        '''You can use this command if you need to inject arguments while on the kernel. You  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___arginj() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___arginj", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;calc&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''calc command
        '''
        '''Summary: You can calculate expressions
        '''
        '''Description
        '''
        '''If you need help on how to calculate expressions when multiplying and dividing large numbers, or if you need to calculate expressions faster, this command is for you.
        '''
        '''It uses the Central Processing Unit (CPU) to process and evaluate expressions, and prints it on the screen when it&apos;s finished. You can&apos;t divide a number by zero.        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___calc() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___calc", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;cdir&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''cdir command
        '''
        '''Summary: You can get current directory
        '''
        '''Description
        '''
        '''This command tells you the current working directory.
        '''
        '''Command usage
        '''
        '''* cdir
        '''
        '''Examples
        '''
        '''* cdir (while on /boot): It tells you that you&apos;re on /boot
        '''* cdir (while on the root directory): It tells you that you&apos;re on /
        '''-BODY END-
        '''
        '''-COLOR CONFIGURATION-
        '''cdir=&gt;Green
        '''cdir (while on /boot):=&gt;Yellow
        '''cdir (while on the root d [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___cdir() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___cdir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;chdir&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''chdir command
        '''
        '''Summary: You can change your current working directory to another directory
        '''
        '''Description
        '''
        '''You can change your working directory to another directory to execute listing commands, removing files, or creating directories on another directory.
        '''
        '''Command usage
        '''
        '''* chdir (directory)
        '''* chdir ..
        '''
        '''Examples
        '''
        '''* chdir boot: It changes your working directory to /boot
        '''* chdir ..: It goe [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___chdir() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___chdir", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;chhostname&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''chhostname command
        '''
        '''Summary: You can change your host name to another name
        '''
        '''Description
        '''
        '''If you&apos;re planning to change your host name to another name, this command is for you.
        '''
        '''This command used to change your host name and resets it everytime you reboot the kernel, but now it stores it in the config file as soon as you change your host name.
        '''
        '''This version of the kernel finally allows ho [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___chhostname() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___chhostname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;chmal&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''chmal command
        '''
        '''Summary: You can change your message of the day after log-in
        '''
        '''Description
        '''
        '''If you don&apos;t like the default message of the day after log-in that is generated by the kernel, then you can use this command to change the message and store it permanently on the config file.
        '''
        '''It also has placeholder support, like if you have &lt;shortdate&gt; and &lt;longtime&gt; placeholders, the &lt;shortdate&gt; placeh [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___chmal() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___chmal", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;chmotd&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''chmotd command
        '''
        '''Summary: You can change your message of the day
        '''
        '''Description
        '''
        '''If you don&apos;t like the default message of the day that is generated by the kernel, then you can use this command to change the message and store it permanently on the config file.
        '''
        '''It also has placeholder support, like if you have &lt;shortdate&gt; and &lt;longtime&gt; placeholders, the &lt;shortdate&gt; placeholder changes to the cur [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___chmotd() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___chmotd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;chpwd&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''chpwd command
        '''
        '''Summary: You can change your password or someone else&apos;s password
        '''
        '''Description
        '''
        '''If the password for your account, or for someone else&apos;s account, needs to be changed, then you can use this command to change your password or someone else&apos;s password.
        '''
        '''This is useful if you think that your account or someone else&apos;s account has a bad password or is in the easy password list located on [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___chpwd() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___chpwd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;chusrname&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''chusrname command
        '''
        '''Summary: You can change your username or someone else&apos;s username
        '''
        '''Description
        '''
        '''If your username or someone else&apos;s username needs to be changed to a new username, you need to change them if it&apos;s your username or if someone allows you to change their username to another name.
        '''
        '''You need to specify the current user name before the new user name so the tool knows how to chang [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___chusrname() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___chusrname", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;cls&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''cls command
        '''
        '''Summary: You can clear your screen from clutter
        '''
        '''Description
        '''
        '''If you are trying to focus on one thing and you can&apos;t do it, or if you want the personal info printed by commands hidden, you can clear your screen from clutter to gain focus and reduce eyestrain.
        '''
        '''This is also useful in scripting (not implemented yet)
        '''
        '''Command usage
        '''
        '''* cls
        '''-BODY END-
        '''
        '''-COLOR CONFIGURATION-
        '''cls=&gt;G [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___cls() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___cls", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;debuglog&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''debuglog command
        '''
        '''Summary: You can view kernel debugger logs from the file named kernelDbg.log that is located in your user profile folder
        '''
        '''Description
        '''
        '''This viewer allows you to view your debug logs without first enabling the debugging mode on the kernel. It is useful if you want to report bugs to us in GitHub.
        '''
        '''Before, this command required you to have the debugger turned on in the kernel [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___debuglog() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___debuglog", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;ftp&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''ftp command
        '''
        '''Summary: You can interact with the File Transfer Protocol (FTP) shell to connect to a server and transfer files
        '''
        '''Description
        '''
        '''You can use the FTP shell to connect to your FTP server or the public FTP servers to interact with the files found in the server.
        '''
        '''You can download files to your computer, upload files to the server, manage files by renaming, deleting, etc., and so on.
        '''
        '''For [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___ftp() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___ftp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:FTP command &quot;changelocaldir&quot; or &quot;cdl&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''changelocaldir or cdl FTP command
        '''
        '''Summary: Changes your local directory
        '''
        '''Description
        '''
        '''This command lets you change your local directory in your hard drives to another directory that exists in the subdirectory. However, when specifying .., it goes backwards.
        '''
        '''Command usage
        '''
        '''* changelocaldir/cdl (directory/..)
        '''Examples
        '''
        '''* changelocaldir C:\Users\Owner\Desktop: This will cha [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___FTP_changelocaldir_or_cdl() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___FTP_changelocaldir_or_cdl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:FTP command &quot;changeremotedir&quot; or &quot;cdr&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''changeremotedir or cdr FTP command
        '''
        '''Summary: Changes your remote directory
        '''
        '''Description
        '''
        '''This command lets you change your remote directory in your connected FTP server to another directory that exists in the subdirectory. However, when specifying .., it goes backwards.
        '''
        '''Command usage
        '''
        '''* changeremotedir/cdr (directory/..)
        '''Examples
        '''
        '''* cdr X11/GNOME: This will change your r [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___FTP_changeremotedir_or_cdr() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___FTP_changeremotedir_or_cdr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:FTP command &quot;connect&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''connect FTP command
        '''
        '''Summary: Connects your FTP client to any FTP server that is valid
        '''
        '''Description
        '''
        '''This command must be executed before running any interactive FTP server commands, like download, upload, cdl, cdr, etc.
        '''
        '''This command opens a new session to connect your FTP client to any FTP server that is open to the public, and valid. It then asks for your credentials. Try with anonymous fir [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___FTP_connect() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___FTP_connect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:FTP command &quot;currlocaldir&quot; or &quot;pwdl&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''currlocaldir or pwdl FTP command
        '''
        '''Summary: Gets your current local directory
        '''
        '''Description
        '''
        '''This FTP command tells you what is the local directory you&apos;re currently looking at.
        '''
        '''Command usage
        '''
        '''* currlocaldir
        '''* pwdl
        '''-BODY END-
        '''
        '''-COLOR CONFIGURATION-
        '''currlocaldir=&gt;Green
        '''pwdl=&gt;Green
        '''-COLOR CONFIG END-
        '''
        '''-SECTIONS-
        '''currlocaldir or pwdl FTP command=&gt;SE1
        '''Description=&gt;SE2
        '''Co [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___FTP_currlocaldir_or_pwdl() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___FTP_currlocaldir_or_pwdl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:FTP command &quot;currremotedir&quot; or &quot;pwdr&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''currremotedir or pwdr FTP command
        '''
        '''Summary: Gets your current remote directory
        '''
        '''Description
        '''
        '''This FTP command tells you what is the remote directory in the FTP server you&apos;re currently looking at.
        '''
        '''Command usage
        '''
        '''* currremotedir
        '''* pwdr
        '''-BODY END-
        '''
        '''-COLOR CONFIGURATION-
        '''currremotedir=&gt;Green
        '''pwdr=&gt;Green
        '''-COLOR CONFIG END-
        '''
        '''-SECTIONS-
        '''currremotedir or pwdr FTP command=&gt; [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___FTP_currremotedir_or_pwdr() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___FTP_currremotedir_or_pwdr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:FTP command &quot;delete&quot; or &quot;del&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''delete or del FTP command
        '''
        '''Summary: Removes files or folders
        '''
        '''Description
        '''
        '''If you have logged in to a user that has administrative privileges, you can remove unwanted files, or extra folders, from the server.
        '''
        '''If you deleted a file while there is transmissions going on in the server, people who tries to get the deleted file will never be able to download it again after their download f [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___FTP_delete_or_del() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___FTP_delete_or_del", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:FTP command &quot;disconnect&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''disconnect FTP command
        '''
        '''Summary: Disconnects from the current working server
        '''
        '''Description
        '''
        '''This command sends the quit command to the FTP server so the server knows that you&apos;re going away. It basically disconnects you from the server to connect to the server again or re-connect to the last server connected.
        '''
        '''Command usage
        '''
        '''* disconnect
        '''-BODY END-
        '''
        '''-COLOR CONFIGURATION-
        '''disconnect=&gt;Gre [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___FTP_disconnect() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___FTP_disconnect", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:FTP command &quot;download&quot; or &quot;get&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''download or get FTP command
        '''
        '''Summary: Downloads a file from the current working directory
        '''
        '''Description
        '''
        '''Downloads the binary or text file and saves it to the current working local directory for you to use the downloaded file that is provided in the FTP server.
        '''
        '''Command usage
        '''
        '''* download/get (file)
        '''Examples
        '''
        '''* download text.txt: Downloads the text file named &quot;text.txt&quot;
        '''* get sha [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___FTP_download_or_get() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___FTP_download_or_get", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:FTP command &quot;listlocal&quot; or &quot;lsl&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''listlocal or lsl FTP command
        '''
        '''Summary: Lists the contents of the current folder or the folder provided
        '''
        '''Description
        '''
        '''You can see the list of the files and sub-directories contained in the current working directory if no directories are specified, or in the specified directory, if specified.
        '''
        '''You can also see the list of the files and sub-directories contained in the previous directo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___FTP_listlocal_or_lsl() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___FTP_listlocal_or_lsl", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:FTP command &quot;listremote&quot; or &quot;lsr&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''listremote or lsr FTP command
        '''
        '''Summary: Lists the contents of the current folder or the folder provided
        '''
        '''Description
        '''
        '''You can see the list of the files and sub-directories contained in the current working directory if no directories are specified, or in the specified directory, if specified.
        '''
        '''You can also see the list of the files and sub-directories contained in the previous direc [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___FTP_listremote_or_lsr() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___FTP_listremote_or_lsr", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:FTP command &quot;rename&quot; or &quot;ren&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''rename or ren FTP command
        '''
        '''Summary: Renames the folder or file in the server
        '''
        '''Description
        '''
        '''You can rename the folder or file in the server when they&apos;re named incorrectly in the server. You need to have administrative privileges to run this command.
        '''
        '''Command usage
        '''
        '''* rename/ren (oldFile) (newFile)
        '''Examples
        '''
        '''* rename shagnhai.png shanghai.png: Renames the file &quot;shagnhai.png&quot; to &quot;sha [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___FTP_rename_or_ren() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___FTP_rename_or_ren", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:FTP command &quot;upload&quot; or &quot;put&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''upload or put FTP command
        '''
        '''Summary: Uploads the file to the server
        '''
        '''Description
        '''
        '''If you need to add your local files in your current working directory to the current working server directory, you must have administrative privileges to add files.
        '''
        '''For example, if you&apos;re adding the picture of the New Delhi city using the PNG format, you need to upload it to the server for everyone to see [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___FTP_upload_or_put() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___FTP_upload_or_put", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;hwprobe&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''hwprobe command
        '''
        '''Summary: You can make your kernel detect hardware configurations when the kernel didn&apos;t do that on boot
        '''
        '''Description
        '''
        '''You can use this command to make the kernel detect hardware and its configuration settings like BIOS, GPU, RAM, HDD, and CPU. It is only usable when the kernel didn&apos;t probe the hardware and their settings on boot.
        '''
        '''Command usage
        '''
        '''* hwprobe
        '''-BODY END-
        '''
        '''-C [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___hwprobe() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___hwprobe", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;list&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''list command
        '''
        '''Summary: You can list contents inside the current directory, or specified folder
        '''
        '''Description
        '''
        '''If you don&apos;t know what&apos;s in the directory, or on the current directory, you can use this command to list folder contents in the colorful way.
        '''
        '''Command usage
        '''
        '''* list
        '''* list [directory]
        '''
        '''Examples
        '''
        '''* list: This command lists the current working directory contents
        '''* list ..: This com [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___list() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___list", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;loadsaver&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''loadsaver command
        '''
        '''Summary: You can import your screensaver modfiles before setting them as default.
        '''
        '''Description
        '''
        '''This command is required as it compiles the contents of your modfile to see if there is any errors.
        '''
        '''This command imports your screensaver mod files and puts it to the valid screensaver list if your screensaver doesn&apos;t contain any errors from the build system.
        '''
        '''You should ru [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___loadsaver() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___loadsaver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;lockscreen&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''lockscreen command
        '''
        '''Summary: You can lock the screen with the default screensaver to prevent screen burns
        '''
        '''Description
        '''
        '''You can lock your screen and show your default screensaver to confirm that you&apos;re away and will coma back for an hour or more. It then asks for your password for security.
        '''
        '''Command usage
        '''
        '''* lockscreen
        '''-BODY END-
        '''
        '''-COLOR CONFIGURATION-
        '''lockscreen=&gt;Green
        '''-COLOR CONF [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___lockscreen() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___lockscreen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;logout&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''logout command
        '''
        '''Summary: You can log out of your account.
        '''
        '''Description
        '''
        '''If there is a change that requires log-out and log-in for the changes to take effect, you must log off and log back in.
        '''
        '''This command lets you off your account and sign in as somebody else. When you&apos;re finished with your account, and you want to use either the root account, or let someone else use their account, you must  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___logout() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___logout", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;lscomp&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''lscomp command
        '''
        '''Summary: You can list computers, even offline computers, in workgroups and domains
        '''
        '''Description
        '''
        '''If you need to list computers in the workgroup or domains, including the offline computer if the computer joined the domain, you can use this command to get all of the computers without their IP addresses.
        '''
        '''However if you need to list computers only if they&apos;re online, and you want  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___lscomp() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___lscomp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;lsnet&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''lsnet command
        '''
        '''Summary: You can list computers that are online and their IP addresses in domains or workgroups
        '''
        '''Description
        '''
        '''If you want to get all of the computers that joined the workgroup or the domain, you can use this command, but you must first ask for permission if you&apos;re on the public places such as office, school, cafe, etc., otherwise, staff members will disconnect your computer for ge [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___lsnet() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___lsnet", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;lsnettree&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''lsnettree command
        '''
        '''Summary: You can list computers that are online and their IP addresses in domains or workgroups, in the tree form
        '''
        '''Description
        '''
        '''If you want to get all of the computers that joined the workgroup or the domain in the tree form, you can use this command, but you must first ask for permission if you&apos;re on the public places such as office, school, cafe, etc., otherwise, staff m [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___lsnettree() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___lsnettree", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;md&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''md command
        '''
        '''Summary: You can make your directory
        '''
        '''Description
        '''
        '''If you want to organize your files into a folder, you must create a folder.
        '''
        '''This command lets you create a folder in the current working directory.
        '''
        '''Command usage
        '''
        '''* md (folderName)
        '''
        '''Examples
        '''
        '''* md Passwords: This command creates a folder named &quot;Passwords&quot; in the current working directory
        '''-BODY END-
        '''
        '''-COLOR CONFIGURATION-        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___md() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___md", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;netinfo&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''netinfo command
        '''
        '''Summary: You can view the detailed status of the network connection
        '''
        '''Description
        '''
        '''This command lets you view the details about all your wireless/Ethernet adapters, packets, packets that has an error, etc. The information that are printed is diagnostic so if you can&apos;t connect to the Internet, you can use these information to diagnose.
        '''
        '''The sections of the information about ad [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___netinfo() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___netinfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;noaliases&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''noaliases command
        '''
        '''Summary: You can view forbidden aliases.
        '''
        '''Description
        '''
        '''This command lets you view the commands that you shouldn&apos;t create an alias for, because they&apos;re forbidden for making issues, like aliasing the &quot;alias&quot; command.
        '''
        '''Command usage
        '''
        '''* noaliases
        '''-BODY END-
        '''
        '''-COLOR CONFIGURATION-
        '''noaliases=&gt;Green
        '''-COLOR CONFIG END-
        '''
        '''-SECTIONS-
        '''noaliases command=&gt;SE1
        '''Description=&gt;S [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___noaliases() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___noaliases", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;perm&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''perm command
        '''
        '''Summary: Manages permissions for your user or other users
        '''
        '''Description
        '''
        '''If you want to manage permissions for your user or other users, or if you want to prevent the user from being logged on, use this command.
        '''
        '''This command lets you manage permissions whether the administrative privileges are on or off, or if the user is disabled or not.
        '''
        '''Command usage
        '''
        '''* perm (userName) (Adm [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___perm() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___perm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;ping&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''ping command
        '''
        '''Summary: Checks for server if it&apos;s offline/online
        '''
        '''Description
        '''
        '''If you can&apos;t reach the server, or if you want to know if it&apos;s offline or online, or if you want to see how far the website is, use this command.
        '''
        '''This command allows you to send the ping request to the server, and the server responds if it is online. It can be repeated by the optional argument.
        '''
        '''Command usage
        '''
        '''* p [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___ping() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___ping", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;rd&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''rd command
        '''
        '''Summary: Removes directory from current working directory
        '''
        '''Description
        '''
        '''This command lets you remove a directory from your current working directory. Currently, all of the kernel folders and files are re-generated everytime you tried to remove kernel folders and files and tried rebooting.
        '''
        '''When the real file system is being implemented, it will really remove directories.
        '''
        '''Command us [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___rd() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___rd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;read&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''read command
        '''
        '''Summary: Reads file contents and prints it to the screen
        '''
        '''Description
        '''
        '''This command lets you see the file contents in your current working directory. You must specify a file in order to read the contents.
        '''
        '''Command usage
        '''
        '''* read (file)
        '''
        '''Examples
        '''
        '''* read libuesh: It reads file contents of libuesh
        '''-BODY END-
        '''
        '''-COLOR CONFIGURATION-
        '''read (file)=&gt;Green
        '''read libuesh:=&gt;Yellow
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___read() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___read", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;reboot&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''reboot command
        '''
        '''Summary: Restarts the kernel
        '''
        '''Description
        '''
        '''This command restarts your simulated kernel and reloads all the config that are not loaded using reloadconfig. This is especially useful if you want to change colors of text, set arguments into the kernel, inject arguments, and so on.
        '''
        '''WARNING: There is no file system syncing because the current kernel version doesn&apos;t have the real fi [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___reboot() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___reboot", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;reloadconfig&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''reloadconfig command
        '''
        '''Summary: Reloads the kernel configuration
        '''
        '''Description
        '''
        '''This command reloads the kernel settings and tries to conserve restarts and reflect the changes immediately. If the changes are not reflected, reboot the kernel.
        '''
        '''Command usage
        '''
        '''* reloadconfig
        '''-BODY END-
        '''
        '''-COLOR CONFIGURATION-
        '''reloadconfig=&gt;Green
        '''-COLOR CONFIG END-
        '''
        '''-SECTIONS-
        '''reloadconfig command=&gt;S [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___reloadconfig() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___reloadconfig", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;rmuser&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''rmuser command
        '''
        '''Summary: Removes uninvited or redundant user
        '''
        '''Description
        '''
        '''This command lets you remove the uninvited or redundant user from the user dictionary that is initialized at the start of the kernel. It also removes password from the removed user if it has one.
        '''
        '''However you can&apos;t remove your own user that is signed in.
        '''
        '''Command usage
        '''
        '''* rmuser (Username)
        '''
        '''Examples
        '''
        '''* rmuser j [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___rmuser() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___rmuser", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;savescreen&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''savescreen command
        '''
        '''Summary: Launches your current screen saver
        '''
        '''Description
        '''
        '''This command can protect your LCD screen from burn-in and shows you the current screensaver that is set by you or by the kernel. However it doesn&apos;t lock the user account, so we recommend to lock your screen for any purposes, unless you&apos;re testing your own screensaver from the screensaver modfile.
        '''
        '''Command usage        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___savescreen() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___savescreen", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;scical&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''scical command
        '''
        '''Summary: Allows you to evaluate more advanced expressions
        '''
        '''Description
        '''
        '''You can use the scientific calculator to evaluate advanced expressions, such as getting the square root of numbers, etc.
        '''
        '''Currently, this command uses the DataTable() class to evaluate expressions. Look at this documentation:
        '''
        '''https://docs.microsoft.com/dotnet/api/system.data.datacolumn.expression
        '''
        '''We  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___scical() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___scical", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;setcolors&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''setcolors command
        '''
        '''Summary: You can set the kernel colors
        '''
        '''Description
        '''
        '''This command allows you to set the kernel text colors, including the kernel error message, input message, license text, general text, etc. It also lets you set the background color to make your kernel look more personalized.
        '''
        '''This command probes colors from ConsoleColor enum values known as integers. This list shows yo [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___setcolors() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___setcolors", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;setsaver&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''setsaver command
        '''
        '''Summary: Sets your default screensaver as your own screensaver or built-in savers
        '''
        '''Description
        '''
        '''You can set your default screensaver as your own screensaver by the modfile or built-in savers such as matrix, disco, and colorMix.
        '''
        '''* matrix: Displays the basic matrix that prints between 0 and 1 in green text color
        '''* disco: Displays the disco lights
        '''* colorMix: It changes th [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___setsaver() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___setsaver", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;setthemes&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''setthemes command
        '''
        '''Summary: Sets your theme
        '''
        '''Description
        '''
        '''You can personalize your kernel using themes, which contains the color sets to set colors. The available themes are:
        '''
        '''* Default: The default kernel color set
        '''* RedConsole: Your console will be red after setting to it
        '''* Bluespire: Enjoy your blue console
        '''* Hacker: If you&apos;re a hacker, set this theme to make your console look more l [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___setthemes() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___setthemes", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;showmotd&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''showmotd command
        '''
        '''Summary: Shows your message of the day
        '''
        '''Description
        '''
        '''This command shows your message of the day before log-in and parses the placeholders in the MOTD if found.
        '''
        '''Command usage
        '''
        '''* showmotd
        '''-BODY END-
        '''
        '''-COLOR CONFIGURATION-
        '''showmotd=&gt;Green
        '''-COLOR CONFIG END-
        '''
        '''-SECTIONS-
        '''showmotd command=&gt;SE1
        '''Description=&gt;SE2
        '''Command usage=&gt;SE2
        '''-SECTIONS END-.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___showmotd() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___showmotd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;showtd&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''showtd command
        '''
        '''Summary: Shows the current time and date
        '''
        '''Description
        '''
        '''If you want to know what time is it without repeatedly going into the clock, you can use this command to show you the current time and date, as well as your time zone.
        '''
        '''Command usage
        '''
        '''* showtd
        '''-BODY END-
        '''
        '''-COLOR CONFIGURATION-
        '''showtd=&gt;Green
        '''-COLOR CONFIG END-
        '''
        '''-SECTIONS-
        '''showtd command=&gt;SE1
        '''Description=&gt;SE2
        '''Com [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___showtd() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___showtd", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;showtdzone&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''showtdzone command
        '''
        '''Summary: Shows current time and date in another timezone
        '''
        '''Description
        '''
        '''If you need to know what time is it on another city or country, you can use this tool to tell you the current time and date in another country or city.
        '''
        '''This command is multi-platform, and uses the IANA timezones on Unix systems and the Windows timezone system on Windows.
        '''
        '''For example, if you need [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___showtdzone() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___showtdzone", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;shutdown&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''shutdown command
        '''
        '''Summary: Shuts down your computer
        '''
        '''Description
        '''
        '''If you&apos;re finished with everything and don&apos;t want to do something else on your computer, instead of leaving it on to consume energy and pay more money to the electricity center, you have to use this command to shutdown your computer and conserve power.
        '''
        '''Command usage
        '''
        '''* shutdown
        '''-BODY END-
        '''
        '''-COLOR CONFIGURATION-
        '''shutdow [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___shutdown() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___shutdown", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;sysinfo&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''sysinfo command
        '''
        '''Summary: Gets your system information
        '''
        '''Description
        '''
        '''This command lets you see your kernel configuration, as well as your MOTD, MAL, host name, user name, and hardware information.
        '''
        '''This command is useful for bug reports and crash reports.
        '''
        '''Command usage
        '''
        '''* sysinfo
        '''-BODY END-
        '''
        '''-COLOR CONFIGURATION-
        '''sysinfo=&gt;Green
        '''-COLOR CONFIG END-
        '''
        '''-SECTIONS-
        '''sysinfo command=&gt;SE1 [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___sysinfo() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___sysinfo", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;unitconv&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''unitconv command
        '''
        '''Summary: Converts units to another unit
        '''
        '''Description
        '''
        '''You can convert your source units to another unit without having to use the Internet.
        '''
        '''If you need to convert currency instead, use the &quot;currency&quot; command.
        '''
        '''The source unit must be supported by the destination unit (eg. km to cm) to convert your provided value, otherwise, it can&apos;t convert. (eg. km to MB)
        '''
        '''Command us [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___unitconv() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___unitconv", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Shell command &quot;useddeps&quot;
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''useddeps command
        '''
        '''Summary: You can get the libraries used in this program
        '''
        '''Description
        '''
        '''Kernel Simulator comes with libraries for easier coding (for devs). We should credit the authors of libraries used. This command shows you the used libraries and their information, license, and author names.
        '''
        '''Command usage
        '''
        '''* useddeps
        '''-BODY END-
        '''
        '''-COLOR CONFIGURATION-
        '''useddeps=&gt;Green
        '''-COLOR CONFIG [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property REV_0_0_1___useddeps() As String
            Get
                Return ResourceManager.GetString("REV_0_0_1___useddeps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to (*MAN START*)
        '''
        '''-TITLE:Screensaver modding guide
        '''-REVISION:0.0.1
        '''-KSLAYOUT:0.0.5.9-OR-ABOVE
        '''
        '''-BODY START-
        '''What is the screensaver for the kernel?
        '''
        '''The screensaver is the idle process that will activate if your computer went idle. You can also see the default screensaver by savescreen that is set by you or by the kernel.
        '''
        '''The screensaver can also be customized, and we&apos;ll teach you how to make your first screensaver, to make from the simplest screensaver to legendary ones.
        '''
        '''Basic modding (screensa [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property Screensaver_modding_guide() As String
            Get
                Return ResourceManager.GetString("Screensaver_modding_guide", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Available commands: {0} &lt;=+=&gt; Comandos disponibles: {0}
        '''Write command: &lt;=+=&gt; Comando de escritura:
        '''Command injection has been cancelled. &lt;=+=&gt; La inyección de comandos ha sido cancelada.
        '''Separate boot arguments with commas without spaces, for example, &apos;motd,gpuprobe&apos; &lt;=+=&gt; Separe los argumentos de arranque con comas sin espacios, por ejemplo, &apos;motd, gpuprobe&apos;
        '''Separate commands on &apos;cmdinject&apos; with colons with spaces, for example, &apos;cmdinject setthemes Hacker : beep 1024 0.5&apos; &lt;=+=&gt; Comandos separados en &apos;c [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property spa() As String
            Get
                Return ResourceManager.GetString("spa", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
