//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nitrocid.Analyzers.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeFixResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeFixResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nitrocid.Analyzers.Resources.CodeFixResources", typeof(CodeFixResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SetConsoleColor(Color, true) from KernelColorTools.
        /// </summary>
        internal static string ConsoleBackColorUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("ConsoleBackColorUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SetConsoleColor(Color) from KernelColorTools.
        /// </summary>
        internal static string ConsoleForeColorUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("ConsoleForeColorUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ReadLine() from Input.
        /// </summary>
        internal static string ConsoleReadLineUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("ConsoleReadLineUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ConsoleExtensions.ResetColors().
        /// </summary>
        internal static string ConsoleResetColorUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("ConsoleResetColorUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use SetTitle() from ConsoleExtensions.
        /// </summary>
        internal static string ConsoleTitleUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("ConsoleTitleUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use ConsoleWrapper.
        /// </summary>
        internal static string ConsoleWrapperUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("ConsoleWrapperUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TWC.Write().
        /// </summary>
        internal static string ConsoleWriteLineUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("ConsoleWriteLineUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TWC.Write().
        /// </summary>
        internal static string ConsoleWriteUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("ConsoleWriteUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use CultureManager.CurrentCultureName.
        /// </summary>
        internal static string CurrentUICultureGetNameUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("CurrentUICultureGetNameUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use CultureManager.CurrentCulture.
        /// </summary>
        internal static string CurrentUICultureGetUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("CurrentUICultureGetUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use CultureManager.UpdateCulture.
        /// </summary>
        internal static string CurrentUICultureSetUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("CurrentUICultureSetUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use FilesystemTools.MakeDirectory().
        /// </summary>
        internal static string DirectoryCreateDirectoryUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("DirectoryCreateDirectoryUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use FilesystemTools.RemoveDirectory().
        /// </summary>
        internal static string DirectoryDeleteUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("DirectoryDeleteUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use FilesystemTools.FolderExists().
        /// </summary>
        internal static string DirectoryExistsUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("DirectoryExistsUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use FilesystemTools.GetFileSystemEntries().
        /// </summary>
        internal static string DirectoryGetFileSystemEntriesAltUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("DirectoryGetFileSystemEntriesAltUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use FilesystemTools.CreateList().
        /// </summary>
        internal static string DirectoryGetFileSystemEntriesUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("DirectoryGetFileSystemEntriesUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use FilesystemTools.CopyFileOrDir().
        /// </summary>
        internal static string FileCopyUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("FileCopyUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use FilesystemTools.MakeFile().
        /// </summary>
        internal static string FileCreateUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("FileCreateUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use FilesystemTools.RemoveFile().
        /// </summary>
        internal static string FileDeleteUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("FileDeleteUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use FilesystemTools.FileExists().
        /// </summary>
        internal static string FileExistsUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("FileExistsUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use FilesystemTools.MoveFileOrDir().
        /// </summary>
        internal static string FileMoveUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("FileMoveUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use NetworkTools.NetworkAvailable.
        /// </summary>
        internal static string GetIsNetworkAvailableUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("GetIsNetworkAvailableUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use KernelPlatform.IsOnUnix().
        /// </summary>
        internal static string IsOsPlatformLinuxUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("IsOsPlatformLinuxUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use KernelPlatform.IsOnMacOs().
        /// </summary>
        internal static string IsOsPlatformOSXUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("IsOsPlatformOSXUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use KernelPlatform.IsOnWindows().
        /// </summary>
        internal static string IsOsPlatformWindowsUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("IsOsPlatformWindowsUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TimeDateRenderers.RenderDate().
        /// </summary>
        internal static string KernelDateTimeToDateStringUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("KernelDateTimeToDateStringUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TimeDateRenderersUtc.RenderDateUtc().
        /// </summary>
        internal static string KernelDateTimeToDateStringUtcUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("KernelDateTimeToDateStringUtcUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TimeDateRenderers.Render().
        /// </summary>
        internal static string KernelDateTimeToStringUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("KernelDateTimeToStringUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TimeDateRenderersUtc.RenderUtc().
        /// </summary>
        internal static string KernelDateTimeToStringUtcUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("KernelDateTimeToStringUtcUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TimeDateRenderers.RenderTime().
        /// </summary>
        internal static string KernelDateTimeToTimeStringUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("KernelDateTimeToTimeStringUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TimeDateRenderersUtc.RenderTimeUtc().
        /// </summary>
        internal static string KernelDateTimeToTimeStringUtcUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("KernelDateTimeToTimeStringUtcUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TextTools.SplitNewLinesOld().
        /// </summary>
        internal static string NewLineSplitCharManagerNewLineUsageAltCodeFixTitle {
            get {
                return ResourceManager.GetString("NewLineSplitCharManagerNewLineUsageAltCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TextTools.SplitNewLines().
        /// </summary>
        internal static string NewLineSplitCharManagerNewLineUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("NewLineSplitCharManagerNewLineUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TextTools.SplitNewLinesOld().
        /// </summary>
        internal static string NewLineSplitEnvironmentNewLineUsageAltCodeFixTitle {
            get {
                return ResourceManager.GetString("NewLineSplitEnvironmentNewLineUsageAltCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TextTools.SplitNewLines().
        /// </summary>
        internal static string NewLineSplitEnvironmentNewLineUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("NewLineSplitEnvironmentNewLineUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TextTools.SplitNewLinesOld().
        /// </summary>
        internal static string NewLineSplitLinuxLiteralUsageAltCodeFixTitle {
            get {
                return ResourceManager.GetString("NewLineSplitLinuxLiteralUsageAltCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TextTools.SplitNewLines().
        /// </summary>
        internal static string NewLineSplitLinuxLiteralUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("NewLineSplitLinuxLiteralUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TextTools.SplitNewLinesOld().
        /// </summary>
        internal static string NewLineSplitMacOS9LiteralUsageAltCodeFixTitle {
            get {
                return ResourceManager.GetString("NewLineSplitMacOS9LiteralUsageAltCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TextTools.SplitNewLines().
        /// </summary>
        internal static string NewLineSplitMacOS9LiteralUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("NewLineSplitMacOS9LiteralUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TextTools.SplitNewLines().
        /// </summary>
        internal static string NewLineSplitOldUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("NewLineSplitOldUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TextTools.SplitNewLinesOld().
        /// </summary>
        internal static string NewLineSplitWindowsLiteralUsageAltCodeFixTitle {
            get {
                return ResourceManager.GetString("NewLineSplitWindowsLiteralUsageAltCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TextTools.SplitNewLines().
        /// </summary>
        internal static string NewLineSplitWindowsLiteralUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("NewLineSplitWindowsLiteralUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use FilesystemTools.Exists().
        /// </summary>
        internal static string PathExistsUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("PathExistsUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use Filesystem.NeutralizePath().
        /// </summary>
        internal static string PathGetFullPathUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("PathGetFullPathUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use FilesystemTools.GetInvalidPathChars().
        /// </summary>
        internal static string PathGetInvalidPathCharsUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("PathGetInvalidPathCharsUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use FilesystemTools.Rooted().
        /// </summary>
        internal static string PathIsPathRootedUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("PathIsPathRootedUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use KernelPlatform.IsOnUnix().
        /// </summary>
        internal static string PlatformIdUnixUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("PlatformIdUnixUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use KernelPlatform.IsOnWindows().
        /// </summary>
        internal static string PlatformIdWin32NtUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("PlatformIdWin32NtUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use KernelPlatform.IsRunningFromScreen().
        /// </summary>
        internal static string ScreenUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("ScreenUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TextTools.FormatString().
        /// </summary>
        internal static string StringFormatCodeFixTitle {
            get {
                return ResourceManager.GetString("StringFormatCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use KernelPlatform.GetTerminalEmulator().
        /// </summary>
        internal static string TermProgramUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("TermProgramUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use KernelPlatform.GetTerminalType().
        /// </summary>
        internal static string TermUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("TermUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use TimeZones.GetCurrentZoneInfo().
        /// </summary>
        internal static string TimeZoneInfoLocalUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("TimeZoneInfoLocalUsageCodeFixTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use KernelPlatform.IsRunningFromTmux().
        /// </summary>
        internal static string TmuxUsageCodeFixTitle {
            get {
                return ResourceManager.GetString("TmuxUsageCodeFixTitle", resourceCulture);
            }
        }
    }
}
