//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nitrocid.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ThemesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ThemesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nitrocid.Resources.ThemesResources", typeof(ThemesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Metadata&quot;: {
        ///        &quot;Name&quot;: &quot;Default&quot;,
        ///        &quot;Description&quot;: &quot;The default theme for the kernel&quot;,
        ///        &quot;Localizable&quot;: true,
        ///        &quot;Category&quot;: &quot;Standard&quot;
        ///    },
        ///    &quot;InputColor&quot;: &quot;15&quot;,
        ///    &quot;LicenseColor&quot;: &quot;15&quot;,
        ///    &quot;ContKernelErrorColor&quot;: &quot;11&quot;,
        ///    &quot;UncontKernelErrorColor&quot;: &quot;9&quot;,
        ///    &quot;HostNameShellColor&quot;: &quot;2&quot;,
        ///    &quot;UserNameShellColor&quot;: &quot;10&quot;,
        ///    &quot;BackgroundColor&quot;: &quot;0&quot;,
        ///    &quot;NeutralTextColor&quot;: &quot;7&quot;,
        ///    &quot;ListEntryColor&quot;: &quot;3&quot;,
        ///    &quot;ListValueColor&quot;: &quot;8&quot;,
        ///    &quot;StageColor&quot;: &quot;10&quot;,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Default {
            get {
                return ResourceManager.GetString("Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Metadata&quot;: {
        ///        &quot;Name&quot;: &quot;Dynamic&quot;,
        ///        &quot;Description&quot;: &quot;Accents everywhere!&quot;,
        ///        &quot;Localizable&quot;: true,
        ///        &quot;Category&quot;: &quot;Exciting&quot;,
        ///        &quot;UseAccentTypes&quot;: [
        ///            &quot;HostNameShellColor&quot;,
        ///            &quot;UserNameShellColor&quot;,
        ///            &quot;NeutralTextColor&quot;,
        ///            &quot;ListEntryColor&quot;,
        ///            &quot;StageColor&quot;,
        ///            &quot;BannerColor&quot;,
        ///            &quot;NotificationTitleColor&quot;,
        ///            &quot;SuccessColor&quot;,
        ///            &quot;UserDollarColor&quot;,
        ///            &quot;SeparatorTextColor&quot;,        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Dynamic {
            get {
                return ResourceManager.GetString("Dynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Metadata&quot;: {
        ///        &quot;Name&quot;: &quot;Nitric Acid - HNO3&quot;,
        ///        &quot;Description&quot;: &quot;Colorless, fuming, and highly corrosive liquid&quot;,
        ///        &quot;Localizable&quot;: true,
        ///        &quot;Category&quot;: &quot;Mesmerizing&quot;
        ///    },
        ///    &quot;InputColor&quot;: &quot;#AC9B03&quot;,
        ///    &quot;LicenseColor&quot;: &quot;#AC9B03&quot;,
        ///    &quot;ContKernelErrorColor&quot;: &quot;#AC9B03&quot;,
        ///    &quot;UncontKernelErrorColor&quot;: &quot;#AC9B03&quot;,
        ///    &quot;HostNameShellColor&quot;: &quot;#AC9B03&quot;,
        ///    &quot;UserNameShellColor&quot;: &quot;#AC9B03&quot;,
        ///    &quot;BackgroundColor&quot;: &quot;#0A0A00&quot;,
        ///    &quot;NeutralTextColor&quot;: &quot;#AC9B03&quot;,
        ///    &quot;ListEntr [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NitricAcid {
            get {
                return ResourceManager.GetString("NitricAcid", resourceCulture);
            }
        }
    }
}
