.\" 
.\"    Nitrocid KS  Copyright (C) 2018-2023  Aptivi
.\" 
.\"    Nitrocid KS is free software: you can redistribute it and/or modify
.\"    it under the terms of the GNU General Public License as published by
.\"    the Free Software Foundation, either version 3 of the License, or
.\"    (at your option) any later version.
.\"
.\"    Nitrocid KS is distributed in the hope that it will be useful,
.\"    but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"    GNU General Public License for more details.
.\"
.\"    You should have received a copy of the GNU General Public License
.\"    along with this program.  If not, see <https://www.gnu.org/licenses/>.
.\" 

.TH ks\-jl 1 "3 Dec 2023" "0.1.0-Man1.1" "Nitrocid KS - Nitrocid.LocaleGen"
.SH NAME
        ks\-jl \- Locale Generator for Nitrocid KS
Part of KS \- simulates our future-planned kernel, Nitrocid Kernel
.SH SYNOPSIS
ks\-jl [args]
.SH DESCRIPTION
ks\-jl is the Nitrocid KS locale jsonifier that converts the language text files (whether default or custom) to the JSON format that Nitrocid KS can read.
.SH OPTIONS
To get information about the available options, consult the wiki at https://aptivi.gitbook.io/nitrocid-ks-manual/advanced-and-power-users/inner-workings/multilingual-kernel-flow#locale-generator.
.SH AUTHOR
Aptivi (eoflaoevicecity@gmail.com)
