//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nitrocid.LanguagePacks.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LanguageResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nitrocid.LanguagePacks.Resources.LanguageResources", typeof(LanguageResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Arabic&quot;,
        ///  &quot;Transliterable&quot;: true,
        ///  &quot;Localizations&quot;: [
        ///    &quot;qalib &apos;alwan ghayr salih {0}&quot;,
        ///    &quot;hwprobe: sayatim altahqiq fi al&apos;ajhizat alkhasat bika. arjuk aintazara...&quot;,
        ///    &quot;&apos;udkhul kalimat murur almaswuwl lilsiyanati.&quot;,
        ///    &quot;khata Kernel &apos;athna&apos; altshghyl: {0}&quot;,
        ///    &quot;aldhuer almzdwj: waqt &apos;iieadat altashghil yatajawaz alhadu al&apos;aqsaa almasmuh bih liwaqt &apos;iieadat tashghil alkhata {0}. laqad wajadat eilat nawatin.&quot;,
        ///    &quot;[{0}] halat min aldhiera: tama tamkin &apos;iieadat altashghil nzra [rest of string was truncated]&quot;;.
        /// </summary>
        public static string arb {
            get {
                return ResourceManager.GetString("arb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Arabic&quot;,
        ///  &quot;Transliterable&quot;: true,
        ///  &quot;Localizations&quot;: [
        ///    &quot;قالب ألوان غير صالح {0}&quot;,
        ///    &quot;hwprobe: سيتم التحقيق في الأجهزة الخاصة بك. ارجوك انتظر...&quot;,
        ///    &quot;أدخل كلمة مرور المسؤول للصيانة.&quot;,
        ///    &quot;خطأ Kernel أثناء التشغيل: {0}&quot;,
        ///    &quot;DOUBLE PANIC: وقت إعادة التشغيل يتجاوز الحد الأقصى المسموح به لوقت إعادة تشغيل الخطأ {0}. لقد وجدت علة نواة.&quot;,
        ///    &quot;[{0}] حالة من الذعر: تم تمكين إعادة التشغيل نظرًا لأن مستوى الخطأ هو {0}.&quot;,
        ///    &quot;[{0}] الذعر: وقت إعادة التشغيل: {1} ثانية ، يتجاوز 1 ساعة. [rest of string was truncated]&quot;;.
        /// </summary>
        public static string arb_T {
            get {
                return ResourceManager.GetString("arb_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Chinese&quot;,
        ///  &quot;Transliterable&quot;: true,
        ///  &quot;Localizations&quot;: [
        ///    &quot;Wúxiào de yánsè múbǎn {0}&quot;,
        ///    &quot;hwprobe: Nǐ de yìngjiàn jiāng bèi tàncè. Qǐng nàixīn děngdài...&quot;,
        ///    &quot;Shūrù guǎnlǐ mìmǎ jìnxíng wéihù.&quot;,
        ///    &quot;Yǐndǎo shí chūxiàn nèihé cuòwù: {0}&quot;,
        ///    &quot;DOUBLE PANIC: Chóngxīn qǐdòng shíjiān chāoguò yǔnxǔ de zuìdà {0} cuòwù chóngqǐ shíjiān. Nǐ fāxiànle yīgè nèihé cuòwù.&quot;,
        ///    &quot;[{0}] Kǒnghuāng: Yóuyú cuòwù jíbié wèi {0} ér chóngqǐ.&quot;,
        ///    &quot;[{0}] Kǒnghuāng: Chóngqǐ shíjiān: {1} Miǎo, chāoguò 1 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string chi {
            get {
                return ResourceManager.GetString("chi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Chinese&quot;,
        ///  &quot;Transliterable&quot;: true,
        ///  &quot;Localizations&quot;: [
        ///    &quot;无效的颜色模板{0}&quot;,
        ///    &quot;hwprobe：将检测您的硬件。请耐心等待...&quot;,
        ///    &quot;输入管理员密码进行维护。&quot;,
        ///    &quot;引导时出现内核错误：{0}&quot;,
        ///    &quot;双重恐慌：重新启动时间超过了允许的最大{0}错误重新启动时间。您发现了一个内核错误。&quot;,
        ///    &quot;[{0}]紧急：由于错误级别为{0}，因此启用了重新启动。&quot;,
        ///    &quot;[{0}]紧急：重新启动时间：{1}秒，超过1小时。设置为1分钟。&quot;,
        ///    &quot;双重恐慌：错误类型{0}无效。&quot;,
        ///    &quot;[{0}]紧急：{1}-按任意键关机。&quot;,
        ///    &quot;[{0}]紧急：{1}-在{2}秒内重新启动...&quot;,
        ///    &quot;双重恐慌：内核错误：{0}&quot;,
        ///    &quot;正在关机...&quot;,
        ///    &quot;正在重新启动...&quot;,
        ///    &quot;错误{0}：{1}&quot;,
        ///    &quot;用户名：&quot;,
        ///    &quot;不允许使用空格。&quot;,
        ///    &quot;不允许有特殊字符。&quot;,
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string chi_T {
            get {
                return ResourceManager.GetString("chi_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Chinese (Traditional)&quot;,
        ///  &quot;Transliterable&quot;: true,
        ///  &quot;Localizations&quot;: [
        ///    &quot;Wúxiào de yánsè múbǎn {0}&quot;,
        ///    &quot;hwprobe: Nín de yìngjiàn jiāng bèi tàncè. Qǐng shāo děng...&quot;,
        ///    &quot;Shūrù guǎnlǐ yuán mìmǎ jìnxíng wéihù.&quot;,
        ///    &quot;Qǐdòng shí chūxiàn nèihé cuòwù:{0}&quot;,
        ///    &quot;Shuāngchóng kǒnghuāng: Chóngxīn qǐdòng shíjiān chāoguò yǔnxǔ de zuìdà {0} cuòwù chóngxīn qǐdòng shíjiān. Nín fāxiànle yīgè nèihé cuòwù.&quot;,
        ///    &quot;[{0}] Kǒnghuāng: Yóuyú cuòwù jíbié wèi {0}, chóngxīn qǐdòng yǐ qǐyòng.&quot;,
        ///    &quot;[{0}] [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cnt {
            get {
                return ResourceManager.GetString("cnt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Chinese (Traditional)&quot;,
        ///  &quot;Transliterable&quot;: true,
        ///  &quot;Localizations&quot;: [
        ///    &quot;無效的顏色模板 {0}&quot;,
        ///    &quot;hwprobe：您的硬件將被探測。請稍等...&quot;,
        ///    &quot;輸入管理員密碼進行維護。&quot;,
        ///    &quot;啟動時出現內核錯誤：{0}&quot;,
        ///    &quot;雙重恐慌：重新啟動時間超過允許的最大 {0} 錯誤重新啟動時間。您發現了一個內核錯誤。&quot;,
        ///    &quot;[{0}] 恐慌：由於錯誤級別為 {0}，重新啟動已啟用。&quot;,
        ///    &quot;[{0}] 恐慌：重啟時間：{1} 秒，超過 1 小時。設置為 1 分鐘。&quot;,
        ///    &quot;雙重恐慌：錯誤類型 {0} 無效。&quot;,
        ///    &quot;[{0}] panic: {1} -- 按任意鍵關機。&quot;,
        ///    &quot;[{0}] 恐慌：{1} -- 在 {2} 秒後重新啟動...&quot;,
        ///    &quot;雙重恐慌：內核錯誤：{0}&quot;,
        ///    &quot;正在關閉...&quot;,
        ///    &quot;正在重新啟動...&quot;,
        ///    &quot;錯誤 {0}：{1}&quot;,
        ///    &quot;用戶名：&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string cnt_T {
            get {
                return ResourceManager.GetString("cnt_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Dutch&quot;,
        ///  &quot;Transliterable&quot;: false,
        ///  &quot;Localizations&quot;: [
        ///    &quot;Ongeldige kleurensjabloon {0}&quot;,
        ///    &quot;hwprobe: Uw hardware wordt ondervraagd. Even geduld aub...&quot;,
        ///    &quot;Voer het beheerderswachtwoord in voor onderhoud.&quot;,
        ///    &quot;Kernelfout tijdens opstarten: {0}&quot;,
        ///    &quot;DUBBELE PANIEK: Herstarttijd overschrijdt de maximale toegestane {0} reboottijd. U vond een kernelbug.&quot;,
        ///    &quot;[{0}] paniek: reboot ingeschakeld vanwege het foutniveau van {0}.&quot;,
        ///    &quot;[{0}] paniek: Tijd om opnieuw op te starten:  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string dtc {
            get {
                return ResourceManager.GetString("dtc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;English&quot;,
        ///  &quot;Transliterable&quot;: false,
        ///  &quot;Localizations&quot;: [
        ///    &quot;Invalid colour template {0}&quot;,
        ///    &quot;hwprobe: Your hardware will be probed. Please wait...&quot;,
        ///    &quot;Enter the admin password for maintenance.&quot;,
        ///    &quot;Kernel Error while booting: {0}&quot;,
        ///    &quot;DOUBLE PANIC: Reboot Time exceeds maximum allowed {0} error reboot time. You found a kernel bug.&quot;,
        ///    &quot;[{0}] panic: Reboot enabled due to error level being {0}.&quot;,
        ///    &quot;[{0}] panic: Time to reboot: {1} seconds, exceeds 1 hour. It is set to 1  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string enk {
            get {
                return ResourceManager.GetString("enk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;French&quot;,
        ///  &quot;Transliterable&quot;: false,
        ///  &quot;Localizations&quot;: [
        ///    &quot;Modèle de couleur non valide {0}&quot;,
        ///    &quot;hwprobe: Votre matériel sera sondé. S&apos;il vous plaît, attendez...&quot;,
        ///    &quot;Entrez le mot de passe administrateur pour la maintenance.&quot;,
        ///    &quot;Erreur du noyau lors du démarrage: {0}&quot;,
        ///    &quot;DOUBLE PANIQUE: le temps de redémarrage dépasse le temps de redémarrage maximal autorisé {0}. Vous avez trouvé un bogue dans le noyau.&quot;,
        ///    &quot;[{0}] panique: le redémarrage est activé car le niveau d&apos;erreu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string fre {
            get {
                return ResourceManager.GetString("fre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;German&quot;,
        ///  &quot;Transliterable&quot;: false,
        ///  &quot;Localizations&quot;: [
        ///    &quot;Ungültige Farbvorlage {0}&quot;,
        ///    &quot;hwprobe: Ihre Hardware wird geprüft. Bitte warten ...&quot;,
        ///    &quot;Geben Sie das Administratorkennwort für die Wartung ein.&quot;,
        ///    &quot;Kernelfehler beim Booten: {0}&quot;,
        ///    &quot;DOUBLE PANIC: Die Neustartzeit überschreitet die maximal erlaubte Fehlerzeit für den Neustart von {0}. Du hast einen Kernel-Fehler gefunden.&quot;,
        ///    &quot;[{0}] panic: Neustart aufgrund der Fehlerstufe {0} aktiviert.&quot;,
        ///    &quot;[{0}] panic: Ze [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ger {
            get {
                return ResourceManager.GetString("ger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Greek&quot;,
        ///  &quot;Transliterable&quot;: false,
        ///  &quot;Localizations&quot;: [
        ///    &quot;Μη έγκυρο χρωματικό πρότυπο {0}&quot;,
        ///    &quot;hwprobe: Το υλικό σας θα διερευνηθεί. Παρακαλώ περιμένετε...&quot;,
        ///    &quot;Εισαγάγετε τον κωδικό πρόσβασης διαχειριστή για συντήρηση.&quot;,
        ///    &quot;Σφάλμα πυρήνα κατά την εκκίνηση: {0}&quot;,
        ///    &quot;ΔΙΠΛΟΣ ΠΑΝΙΚΟΣ: Ο χρόνος επανεκκίνησης υπερβαίνει τον μέγιστο επιτρεπόμενο χρόνο επανεκκίνησης σφάλματος {0}. Βρήκατε ένα σφάλμα πυρήνα.&quot;,
        ///    &quot;[{0}] πανικός: Η επανεκκίνηση ενεργοποιήθηκε λόγω του επιπέδου σφάλμ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string grk {
            get {
                return ResourceManager.GetString("grk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Hindi&quot;,
        ///  &quot;Transliterable&quot;: true,
        ///  &quot;Localizations&quot;: [
        ///    &quot;amaany rang tempalet {0}&quot;,
        ///    &quot;hwprobai: aapake haardaveyar kee jaanch kee jaegee. krpaya prateeksha karen ...&quot;,
        ///    &quot;rakharakhaav ke lie vyavasthaapak paasavard darj karen.&quot;,
        ///    &quot;booting ke dauraan karnel truti: {0}&quot;,
        ///    &quot;dabal painik: reeboot taim adhikatam sveekrt {0} truti riboot samay se adhik hai. aapako karnel bag mila.&quot;,
        ///    &quot;[{0}] aatank: truti star {0} hone ke kaaran saksham reeboot.&quot;,
        ///    &quot;[{0}] dahashat: reeboo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ind {
            get {
                return ResourceManager.GetString("ind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Hindi&quot;,
        ///  &quot;Transliterable&quot;: true,
        ///  &quot;Localizations&quot;: [
        ///    &quot;अमान्य रंग टेम्पलेट {0}&quot;,
        ///    &quot;hwprobe: आपके हार्डवेयर की जांच की जाएगी। कृपया प्रतीक्षा करें...&quot;,
        ///    &quot;रखरखाव के लिए व्यवस्थापक पासवर्ड दर्ज करें।&quot;,
        ///    &quot;बूट करते समय कर्नेल त्रुटि: {0}&quot;,
        ///    &quot;दोहरा PANIC: रिबूट समय अधिकतम अनुमत {0} त्रुटि रिबूट समय से अधिक है। आपको एक कर्नेल बग मिला।&quot;,
        ///    &quot;[{0}] घबराहट: त्रुटि स्तर {0} होने के कारण रिबूट सक्षम।&quot;,
        ///    &quot;[{0}] घबराहट: रिबूट करने का समय: {1} सेकंड, 1 घंटे से अधिक। यह 1 मिनट के [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ind_T {
            get {
                return ResourceManager.GetString("ind_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Italian&quot;,
        ///  &quot;Transliterable&quot;: false,
        ///  &quot;Localizations&quot;: [
        ///    &quot;Modello di colore non valido {0}&quot;,
        ///    &quot;hwprobe: il tuo hardware verrà verificato. Attendere prego...&quot;,
        ///    &quot;Immettere la password dell&apos;amministratore per la manutenzione.&quot;,
        ///    &quot;Errore del kernel durante l&apos;avvio: {0}&quot;,
        ///    &quot;DOPPIO PANICO: il tempo di riavvio supera il tempo massimo consentito per il riavvio dell&apos;errore {0}. Hai trovato un bug del kernel.&quot;,
        ///    &quot;[{0}] panico: riavvio attivato a causa del livello di errore { [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ita {
            get {
                return ResourceManager.GetString("ita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Japanese&quot;,
        ///  &quot;Transliterable&quot;: false,
        ///  &quot;Localizations&quot;: [
        ///    &quot;無効なカラーテンプレート{0}&quot;,
        ///    &quot;hwprobe：ハードウェアがプローブされます。お待ちください...&quot;,
        ///    &quot;メンテナンス用の管理者パスワードを入力します。&quot;,
        ///    &quot;起動中のカーネルエラー：{0}&quot;,
        ///    &quot;ダブルパニック：再起動時間が最大許容{0}エラーの再起動時間を超えています。カーネルのバグを見つけました。&quot;,
        ///    &quot;[{0}]パニック：エラーレベルが{0}であるため、再起動が有効になりました。&quot;,
        ///    &quot;[{0}]パニック：再起動の時間：{1}秒、1時間を超えています。 1分に設定されています。&quot;,
        ///    &quot;ダブルパニック：エラータイプ{0}が無効です。&quot;,
        ///    &quot;[{0}]パニック：{1}-任意のキーを押してシャットダウンします。&quot;,
        ///    &quot;[{0}]パニック：{1}-{2}秒で再起動しています...&quot;,
        ///    &quot;ダブルパニック：カーネルバグ：{0}&quot;,
        ///    &quot;シャ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jpn {
            get {
                return ResourceManager.GetString("jpn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Korean&quot;,
        ///  &quot;Transliterable&quot;: true,
        ///  &quot;Localizations&quot;: [
        ///    &quot;jalmosdoen saegsang tempeullis {0}&quot;,
        ///    &quot;hwprobe : hadeuweeoga geomsadoebnida. gidalyeojuseyo ...&quot;,
        ///    &quot;yuji gwanlileul wihae gwanlija bimilbeonholeul iblyeoghasibsio.&quot;,
        ///    &quot;buting jung keoneol olyu : {0}&quot;,
        ///    &quot;ijung paenig : jaebuting sigan-i choedae heoyong {0} olyu jaebuting sigan-eul chogwahabnida. keoneol beogeuleul balgyeonhaessseubnida.&quot;,
        ///    &quot;[{0}] paenig : olyu lebel-i {0}imeulo jaebuting-i ganeunghabnida.&quot;,
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string kor {
            get {
                return ResourceManager.GetString("kor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Korean&quot;,
        ///  &quot;Transliterable&quot;: true,
        ///  &quot;Localizations&quot;: [
        ///    &quot;잘못된 색상 템플릿 {0}&quot;,
        ///    &quot;hwprobe : 하드웨어가 검사됩니다. 기다려주세요 ...&quot;,
        ///    &quot;유지 관리를 위해 관리자 비밀번호를 입력하십시오.&quot;,
        ///    &quot;부팅 중 커널 오류 : {0}&quot;,
        ///    &quot;이중 패닉 : 재부팅 시간이 최대 허용 {0} 오류 재부팅 시간을 초과합니다. 커널 버그를 발견했습니다.&quot;,
        ///    &quot;[{0}] 패닉 : 오류 레벨이 {0}이므로 재부팅이 가능합니다.&quot;,
        ///    &quot;[{0}] 패닉 : 재부팅 시간 : {1} 초, 1 시간을 초과합니다. 1 분으로 설정되어 있습니다.&quot;,
        ///    &quot;이중 패닉 : 오류 유형 {0}이 (가) 유효하지 않습니다.&quot;,
        ///    &quot;[{0}] 패닉 : {1}-종료하려면 아무 키나 누르십시오.&quot;,
        ///    &quot;[{0}] 패닉 : {1}-{2} 초 후에 재부팅 중 ...&quot;,
        ///    &quot;이중 패닉 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string kor_T {
            get {
                return ResourceManager.GetString("kor_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///    {
        ///        &quot;three&quot;: &quot;arb&quot;,
        ///        &quot;name&quot;: &quot;Arabic&quot;,
        ///        &quot;transliterable&quot;: true,
        ///        &quot;country&quot;: &quot;Syria&quot;
        ///    },
        ///    {
        ///        &quot;three&quot;: &quot;arb-T&quot;,
        ///        &quot;name&quot;: &quot;Arabic&quot;,
        ///        &quot;transliterable&quot;: true,
        ///        &quot;codepage&quot;: 1256,
        ///        &quot;country&quot;: &quot;Syria&quot;
        ///    },
        ///    {
        ///        &quot;three&quot;: &quot;chi&quot;,
        ///        &quot;name&quot;: &quot;Chinese&quot;,
        ///        &quot;transliterable&quot;: true,
        ///        &quot;country&quot;: &quot;China&quot;
        ///    },
        ///    {
        ///        &quot;three&quot;: &quot;chi-T&quot;,
        ///        &quot;name&quot;: &quot;Chinese&quot;,
        ///        &quot;transliterable&quot;: true,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LanguageMetadata {
            get {
                return ResourceManager.GetString("LanguageMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Latin&quot;,
        ///  &quot;Transliterable&quot;: false,
        ///  &quot;Localizations&quot;: [
        ///    &quot;Formulae color invalidae {0}&quot;,
        ///    &quot;hwprobe: Ferramenta tua probabuntur. Please wait...&quot;,
        ///    &quot;Intrant admin password pro tutela.&quot;,
        ///    &quot;Error kernel dum patuissent: {0}&quot;,
        ///    &quot;TUMULUS: Reboot Tempus excedit maximum {0} errorem reboot tempus. Invenisti nucleum cimex.&quot;,
        ///    &quot;[{0}] terror: Reboot para propter errorum gradu {0}.&quot;,
        ///    &quot;[{0}] terror: Tempus ut reboot: {1} secundis, unam horam excedit. I positum est minute.&quot;,
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ltn {
            get {
                return ResourceManager.GetString("ltn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Portuguese&quot;,
        ///  &quot;Transliterable&quot;: false,
        ///  &quot;Localizations&quot;: [
        ///    &quot;Modelo de cor inválido {0}&quot;,
        ///    &quot;hwprobe: Seu hardware será testado. Por favor aguarde ...&quot;,
        ///    &quot;Digite a senha do administrador para manutenção.&quot;,
        ///    &quot;Erro de kernel durante a inicialização: {0}&quot;,
        ///    &quot;PAINEL DUPLO: O tempo de reinicialização excede o tempo máximo permitido de reinicialização do erro {0}. Você encontrou um bug do kernel.&quot;,
        ///    &quot;[{0}] panic: Reinicialização ativada devido ao nível de erro ser {0}.&quot;,
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ptg {
            get {
                return ResourceManager.GetString("ptg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Roman&quot;,
        ///  &quot;Transliterable&quot;: false,
        ///  &quot;Localizations&quot;: [
        ///    &quot;Șablon de culoare nevalid {0}&quot;,
        ///    &quot;hwprobe: hardware-ul dvs. va fi testat. Va rugam asteptati...&quot;,
        ///    &quot;Introduceți parola de administrator pentru întreținere.&quot;,
        ///    &quot;Eroare kernel la pornire: {0}&quot;,
        ///    &quot;PANICĂ DUBLĂ: Timpul de repornire depășește timpul maxim permis de repornire pentru eroare de {0}. Ai găsit o eroare a nucleului.&quot;,
        ///    &quot;[{0}] panică: repornirea a fost activată din cauza nivelului de eroare {0}.&quot;,
        ///    &quot;[{ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string rmn {
            get {
                return ResourceManager.GetString("rmn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Russian&quot;,
        ///  &quot;Transliterable&quot;: true,
        ///  &quot;Localizations&quot;: [
        ///    &quot;Nevernyy tsvetovoy shablon {0}&quot;,
        ///    &quot;hwprobe: Vashe oborudovaniye budet provereno. Pozhaluysta, podozhdite...&quot;,
        ///    &quot;Vvedite parol&apos; administratora dlya obsluzhivaniya.&quot;,
        ///    &quot;Oshibka yadra pri zagruzke: {0}&quot;,
        ///    &quot;DVOYNAYA PANIKA: Vremya perezagruzki prevyshayet maksimal&apos;no dopustimoye vremya perezagruzki {0}. Vy nashli oshibku v yadre.&quot;,
        ///    &quot;[{0}] panika: perezagruzka vklyuchena iz-za urovnya oshibki {0}.&quot;,
        ///    &quot;[{0}] pa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string rus {
            get {
                return ResourceManager.GetString("rus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Russian&quot;,
        ///  &quot;Transliterable&quot;: true,
        ///  &quot;Localizations&quot;: [
        ///    &quot;Неверный цветовой шаблон {0}&quot;,
        ///    &quot;hwprobe: Ваше оборудование будет проверено. Пожалуйста, подождите...&quot;,
        ///    &quot;Введите пароль администратора для обслуживания.&quot;,
        ///    &quot;Ошибка ядра при загрузке: {0}&quot;,
        ///    &quot;ДВОЙНАЯ ПАНИКА: Время перезагрузки превышает максимально допустимое время перезагрузки {0}. Вы нашли ошибку в ядре.&quot;,
        ///    &quot;[{0}] паника: перезагрузка включена из-за уровня ошибки {0}.&quot;,
        ///    &quot;[{0}] паника: время перезагрузки [rest of string was truncated]&quot;;.
        /// </summary>
        public static string rus_T {
            get {
                return ResourceManager.GetString("rus_T", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Name&quot;: &quot;Spanish&quot;,
        ///  &quot;Transliterable&quot;: false,
        ///  &quot;Localizations&quot;: [
        ///    &quot;Plantilla de color no válida {0}&quot;,
        ///    &quot;hwprobe: Su hardware será probado. Por favor espere ...&quot;,
        ///    &quot;Introduzca la contraseña de administrador para el mantenimiento.&quot;,
        ///    &quot;Error del núcleo durante el arranque: {0}&quot;,
        ///    &quot;DOBLE PÁNICO: el tiempo de reinicio excede el máximo permitido {0} tiempo de reinicio de error. Has encontrado un error en el kernel.&quot;,
        ///    &quot;Pánico [{0}]: reinicio habilitado debido a que el nivel de err [rest of string was truncated]&quot;;.
        /// </summary>
        public static string spa {
            get {
                return ResourceManager.GetString("spa", resourceCulture);
            }
        }
    }
}
