.\" 
.\" ﻿   Kernel Simulator  Copyright (C) 2018-2022  Aptivi
.\" 
.\"    Kernel Simulator is free software: you can redistribute it and/or modify
.\"    it under the terms of the GNU General Public License as published by
.\"    the Free Software Foundation, either version 3 of the License, or
.\"    (at your option) any later version.
.\"
.\"    Kernel Simulator is distributed in the hope that it will be useful,
.\"    but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"    GNU General Public License for more details.
.\"
.\"    You should have received a copy of the GNU General Public License
.\"    along with this program.  If not, see <https://www.gnu.org/licenses/>.
.\" 

.TH ks\-converter 1 "5 Feb 2022" "0.0.20.0-Man1.0" "Kernel Simulator - KSConverter"
.SH NAME
        ks\-converter \- converts KS configuration
part of ks \- simulates our future-planned kernel 
.SH SYNOPSIS
ks\-converter
.SH DESCRIPTION
ks\-converter converts the existing KS configurations from the pre\-0.0.15.0 versions to the current versions.
.SH MORE INFORMATION
To get more information about the converter, consult the wiki at https://github.com/Aptivi/NitrocidKS/wiki/KSConverter.
.SH AUTHOR
Aptivi (eoflaoevicecity@gmail.com)
