name: Build Project (Debian Package, Lintian)

on:
  push:
    branches: [ "main", "v0.1.0.x-saas", "v0.1.1.x-saas", "v0.1.2.x-saas", "v0.1.3.x-saas" ]
  pull_request:
    branches: [ "main", "v0.1.0.x-saas", "v0.1.1.x-saas", "v0.1.2.x-saas", "v0.1.3.x-saas" ]

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'true'
      
      - name: Import GPG
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Install required packages
        run: |
          sudo rm /etc/apt/sources.list.d/microsoft-prod.list
          sudo apt autoremove dotnet*
          sudo apt update
          sudo NEEDRESTART_SUSPEND=1 apt install curl locales-all libunwind8-dev libcurl4-openssl-dev dotnet-sdk-8.0 libjack0 libportaudio2 libopenal1 libsdl2-2.0-0 libpulse0 libaudio2 devscripts debhelper-compat dput build-essential
        
      - name: Initialize offline package
        run: |
          chmod +x vnd/initializeoffline.sh
          make init-offline
          make clean
        
      - name: Make original package
        run: |
          mv debian ..
          mv .github ..
          tar cfv ../nitrocid-28_3.1.28.0-0.1.3.0.orig.tar .
          xz ../nitrocid-28_3.1.28.0-0.1.3.0.orig.tar
          mv ../debian .

      - name: Build package
        run: |
          debuild -us -uc
          cp ../*.deb .
        
      - name: Upload package to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Nitrocid-KS-Debian-Package
          path: "*.deb"

      - name: Try to install
        run: |
          sudo apt install ./nitrocid-28_*.deb
